name: Deploy to GitHub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # ใช้เวอร์ชันที่รองรับการติดตั้ง blinker 1.9.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify dependencies
        run: pip list

      - name: Run application
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "Running application..."
          python app.py  # เพิ่มขั้นตอนการตรวจสอบ logs ถ้าจำเป็น

      - name: Check reservation.db status
        run: |
          ls -l  # ตรวจสอบสถานะของไฟล์ reservation.db

      - name: Check GITHUB_TOKEN
        run: echo $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

